mem:
  big_mem_avail: FALSE
  normal_mem_per_core_gb: 4
  big_mem_per_core_gb: 26
tmp_dir: tmp
raws:
  Contigs: "test/assembly.fasta"
  Alignment_metagenomics: "test/mg.reads.sorted.bam"
  Contig_depth: ""
sample: test
outputdir: "test_output4"
db_path: "database"
binning:
  run_mode: 'py_binny' # r_binny or py_binny
  binny:
    kmers: '2,3,4'
    cutoff: 500
  filtering:
    completeness: 40
    purity: 90
