__default__: 
  call: "sbatch"
  nodes: "-N 1"
  partition: "-p batch"
  qos: "--qos normal"
  mem_per_cpu: "--mem-per-cpu "  
  runtime: "-t "
  threads: "-n "

binny:
  partition: "-p batch"

call_contig_depth:
  partition: "-p batch"

